# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  tests: true
  build-tags:
    - test_with_docker_compose
    - test_with_testcontainers

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  misspell:
    locale: US
  unused:
    check-exported: false
  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    - contextcheck
    - deadcode
    - depguard
    - exhaustivestruct
    - forbidigo
    - forcetypeassert
    - gci
    - gochecknoglobals
    - golint
    - gomoddirectives
    - gomnd
    - goerr113
    - ifshort
    - interfacer
    - ireturn
    - lll
    - maligned
    - nosnakecase
    - paralleltest
    - rowserrcheck
    - scopelint
    - structcheck
    - tagliatelle
    - testpackage
    - wastedassign
    - wrapcheck
    - varcheck
    - varnamelen

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - containedctx
        - dupl
        - funlen
        - goconst
        - goerr113
        - gomnd
        - maintidx
        - noctx
        - rowserrcheck
      path: "_test.go"
