version: "2"
run:
  build-tags:
    - test_with_docker_compose
    - test_with_testcontainers
  tests: true
linters:
  default: all
  disable:
    - contextcheck
    - depguard
    - err113
    - forbidigo
    - forcetypeassert
    - gochecknoglobals
    - gomoddirectives
    - ireturn
    - lll
    - mnd
    - paralleltest
    - perfsprint
    - rowserrcheck
    - tagliatelle
    - testpackage
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocyclo:
      min-complexity: 20
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - containedctx
          - dupl
          - err113
          - funlen
          - goconst
          - maintidx
          - mnd
          - noctx
          - rowserrcheck
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
