name: test-with-testcontainers

permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  GO111MODULE: "on"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        mongo-version: [ "4.4", "5.0" ]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Go cache
        uses: actions/cache@v3
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ env.GITHUB_JOB }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ env.GITHUB_JOB }}-${{ hashFiles('**/go.sum') }}
      - run: |
          go mod vendor

      - name: Test
        id: test
        env:
          MONGO_VERSION: "${{ matrix.mongo-version }}"
        run: |
          make test-with-testcontainers
